Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using EstudosApiFront.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace EstudosApiFront.Controllers
{
    public class CategoriasController : Controller
    {
        public string uriBase = "https://estudosapi.azurewebsites.net/Categorias/";
        public IActionResult Index()
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("SessionIdUsuario")))
            {
                return RedirectToAction("Sair", "Usuarios");
            }
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        // [HttpGet]
        // public async Task<ActionResult> IndexAsync()
        // {
        //     try
        //     {
        //         if (string.IsNullOrEmpty(HttpContext.Session.GetString("SessionIdUsuario")))
        //         {
        //             return RedirectToAction("Sair", "Usuarios");
        //         }
        //         string uriComplementar = "GetAll";
        //         HttpClient httpClient = new HttpClient();

        //         HttpResponseMessage response = await httpClient.GetAsync(uriBase + uriComplementar);
        //         string serialized = await response.Content.ReadAsStringAsync();

        //         if (response.StatusCode == System.Net.HttpStatusCode.OK)
        //         {
        //             List<CategoriaViewModel> listaCategorias = await Task.Run(() => JsonConvert.DeserializeObject<List<CategoriaViewModel>>(serialized));

        //             return View(listaCategorias);
        //         }
        //         else
        //         {
        //             throw new System.Exception(serialized);
        //         }
        //     }
        //     catch (System.Exception ex)
        //     {
        //         TempData["MensagemErro"] = ex.Message;
        //         return RedirectToAction("Index");
        //     }
        // }
        [HttpGet]
        public async Task<ActionResult> IndexAsync()
        {
            try
            {
                string usuarioIdStr = HttpContext.Session.GetString("SessionIdUsuario");
                if (string.IsNullOrEmpty(usuarioIdStr))
                {
                    return RedirectToAction("Sair", "Usuarios");
                }

                int usuarioId = int.Parse(usuarioIdStr);  

                string uriComplementar = $"GetByUsuario/{usuarioId}";
                HttpClient httpClient = new HttpClient();

                HttpResponseMessage response = await httpClient.GetAsync(uriBase + uriComplementar);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    List<CategoriaViewModel> listaCategorias = JsonConvert.DeserializeObject<List<CategoriaViewModel>>(serialized);
                    return View(listaCategorias);
                }
                else
                {
                    throw new System.Exception(serialized);
                }
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public async Task<ActionResult> EditAsync(int? id)
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                HttpResponseMessage response = await httpClient.GetAsync(uriBase + id.ToString());

                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    CategoriaViewModel categoria = await Task.Run(() => JsonConvert.DeserializeObject<CategoriaViewModel>(serialized));
                    return View(categoria);
                }
                else
                {
                    throw new System.Exception(serialized);
                }
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public async Task<ActionResult> EditAsync(CategoriaViewModel categoria)
        {
            try
            {
                HttpClient httpClient = new HttpClient();

                var content = new StringContent(JsonConvert.SerializeObject(categoria));
                content.Headers.ContentType = new MediaTypeHeaderValue("application/json");

                HttpResponseMessage response = await httpClient.PutAsync(uriBase, content);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    TempData["Mensagem"] = string.Format("categoria {0}, Id {1} salva com sucesso!", categoria.Nome, serialized);
                    return RedirectToAction("Index");
                }
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public async Task<ActionResult> DetailsAsync(int? id)
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                HttpResponseMessage response = await httpClient.GetAsync(uriBase + id.ToString());
                string serialized = await response.Content.ReadAsStringAsync();
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    CategoriaViewModel categoria = await Task.Run(() => JsonConvert.DeserializeObject<CategoriaViewModel>(serialized));
                    return View(categoria);
                }
                else
                {
                    throw new System.Exception(serialized);
                }
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public async Task<ActionResult> CreateAsync(CategoriaViewModel categoria)
        {
            try
            {
                // Obtém o ID do usuário logado
                string usuarioIdStr = HttpContext.Session.GetString("SessionIdUsuario");
                if (string.IsNullOrEmpty(usuarioIdStr))
                {
                    return RedirectToAction("Sair", "Usuarios");  // Redireciona caso não esteja logado
                }

                int usuarioId = int.Parse(usuarioIdStr);  // Converte o ID do usuário para inteiro

                // Adiciona o ID do usuário à categoria
                categoria.UsuarioId = usuarioId;

                if (categoria.UsuarioId == 0)
                {
                    throw new Exception("Usuário não logado ou ID de usuário inválido.");
                }

                // Cria o conteúdo da requisição com os dados da categoria
                HttpClient httpClient = new HttpClient();
                var content = new StringContent(JsonConvert.SerializeObject(categoria));
                content.Headers.ContentType = new MediaTypeHeaderValue("application/json");

                // Envia a requisição POST para criar a categoria
                HttpResponseMessage response = await httpClient.PostAsync(uriBase, content);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    TempData["Mensagem"] = string.Format("Categoria '{0}' (Id {1}) salva com sucesso!", categoria.Nome, serialized);
                    return RedirectToAction("Index");
                }
                else
                {
                    throw new System.Exception(serialized);
                }
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Create");
            }
        }


        [HttpGet]
        public async Task<ActionResult> DeleteAsync(int id)
        {
            try
            {
                HttpClient httpClient = new HttpClient();

                HttpResponseMessage response = await httpClient.DeleteAsync(uriBase + id.ToString());
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    TempData["Mensagem"] = string.Format("Categoria Id {0} removida com sucesso", id);
                    return RedirectToAction("Index");
                }
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
    }
}

Controllers/TarefasController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using EstudosApiFront.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace EstudosApiFront.Controllers
{
    public class TarefasController : Controller
    {
        public string uriBase = "https://estudosapi.azurewebsites.net/Tarefas/";
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpGet]
        public async Task<ActionResult> IndexAsync()
        {
            try
            {
                string usuarioIdStr = HttpContext.Session.GetString("SessionIdUsuario");
                if (string.IsNullOrEmpty(usuarioIdStr))
                {
                    return RedirectToAction("Sair", "Usuarios");
                }

                int usuarioId = int.Parse(usuarioIdStr);  

                string uriComplementar = $"GetByUsuario2/{usuarioId}";
                HttpClient httpClient = new HttpClient();

                HttpResponseMessage response = await httpClient.GetAsync(uriBase + uriComplementar);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    List<TarefaViewModel> listaTarefas = JsonConvert.DeserializeObject<List<TarefaViewModel>>(serialized);
                    return View(listaTarefas);
                }
                else
                {
                    throw new System.Exception(serialized);
                }
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public async Task<ActionResult> EditAsync(int? id)
        {
            try
            {
                string usuarioIdStr = HttpContext.Session.GetString("SessionIdUsuario");
                int usuarioId = int.Parse(usuarioIdStr);  
                HttpClient httpClient = new HttpClient();
                HttpResponseMessage response = await httpClient.GetAsync(uriBase + id.ToString());

                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    TarefaViewModel tarefa = await Task.Run(() => JsonConvert.DeserializeObject<TarefaViewModel>(serialized));

                    HttpResponseMessage categoriaResponse = await httpClient.GetAsync($"https://estudosapi.azurewebsites.net/Categorias/GetByUsuario/{usuarioId}");
                    string categoriaSerialized = await categoriaResponse.Content.ReadAsStringAsync();
                    List<CategoriaViewModel> categorias = JsonConvert.DeserializeObject<List<CategoriaViewModel>>(categoriaSerialized);
                    ViewBag.Categorias = categorias;


                    return View(tarefa);
                }
                else
                {
                    throw new System.Exception(serialized);
                }
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public async Task<ActionResult> EditAsync(TarefaViewModel tarefa)
        {
            try
            {
                HttpClient httpClient = new HttpClient();

                var content = new StringContent(JsonConvert.SerializeObject(tarefa));
                content.Headers.ContentType = new MediaTypeHeaderValue("application/json");

                HttpResponseMessage response = await httpClient.PutAsync(uriBase, content);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    TempData["Mensagem"] = string.Format("Tarefa {0}, Id {1} salva com sucesso!", tarefa.Nome, serialized);
                    return RedirectToAction("Index");
                }
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public async Task<ActionResult> DetailsAsync(int? id)
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                HttpResponseMessage response = await httpClient.GetAsync(uriBase + id.ToString());
                string serialized = await response.Content.ReadAsStringAsync();
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    TarefaViewModel tarefa = await Task.Run(() => JsonConvert.DeserializeObject<TarefaViewModel>(serialized));
                    return View(tarefa);
                }
                else
                {
                    throw new System.Exception(serialized);
                }
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public async Task<ActionResult> CreateAsync(TarefaViewModel tarefa)
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                var content = new StringContent(JsonConvert.SerializeObject(tarefa));
                content.Headers.ContentType = new MediaTypeHeaderValue("application/json");

                HttpResponseMessage response = await httpClient.PostAsync(uriBase, content);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    TempData["Mensagem"] = string.Format("Tarefa {0}, Id {1} salva com sucesso!", tarefa.Nome, serialized);
                    return RedirectToAction("Index");
                }
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Create");
            }
        }
        [HttpGet]
        public async Task<ActionResult> DeleteAsync(int id)
        {
            try
            {
                HttpClient httpClient = new HttpClient();

                HttpResponseMessage response = await httpClient.DeleteAsync(uriBase + id.ToString());
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    TempData["Mensagem"] = string.Format("Tarefa Id {0} removida com sucesso", id);
                    return RedirectToAction("Index");
                }
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EstudosApi</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EstudosApiFront.styles.css" asp-append-version="true" />
</head>

<body>
    <header class="box-shadow border-bottom">
        @{
            var nomeSessao = new Byte[20];
            bool nomeOK = Context.Session.TryGetValue("SessionIdUsuario", out nomeSessao);
            string sessao = string.Empty;

            var nomeSessaoPerfil = new Byte[20];
            bool perfilOK = Context.Session.TryGetValue("SessionPerfilUsuario", out nomeSessaoPerfil);
            string sessaoPerfil = string.Empty;

            if (nomeOK)
                sessao = System.Text.Encoding.UTF8.GetString(nomeSessao);

            if (perfilOK)
                sessaoPerfil = System.Text.Encoding.UTF8.GetString(nomeSessaoPerfil);


            <div class="container">
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white">
                    <div class="container-fluid ">
                        @if (string.IsNullOrEmpty(sessao))
                        {
                            <a asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="@Url.Content("~/images/study_icon.png")" class="headerImg">
                            </a>
                            <a class="navbar-brand logo-nome" asp-area="" asp-controller="Home" asp-action="Index">EstudosApi</a>
                        }else{
                            <a asp-area="" asp-controller="Categorias" asp-action="Index">
                                <img src="@Url.Content("~/images/study_icon.png")" class="headerImg">
                            </a>
                            <a class="navbar-brand logo-nome" asp-area="" asp-controller="Categorias" asp-action="Index">EstudosApi</a>
                        }
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false"
                            aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1 align-items-center">
                                @if (string.IsNullOrEmpty(sessao))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                            asp-action="Index">Inicio <span class="bar"></span> </a>
                                    </li>
                                }
                                @if (!string.IsNullOrEmpty(sessao))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Categorias"
                                            asp-action="Index">Categorias <span class="bar"></span></a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Tarefas"
                                            asp-action="Index">Tarefas <span class="bar"></span></a>
                                    </li>
                                }
                            </ul>

                            <ul class="navbar-nav align-items-center">
                                @if (!string.IsNullOrEmpty(sessao))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios"
                                            asp-action="IndexInformacoes">Perfil <span class="bar"></span></a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="btn btn-outline-dark leave" asp-area="" asp-controller="Usuarios" asp-action="Sair">Sair<span class="bar"></span></a>
                                    </li>
                                }
                                @if (string.IsNullOrEmpty(sessao))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios"
                                            asp-action="Index">Registrar-se <span class="bar"></span></a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="btn btn-primary btn-lg text-white" asp-area="" asp-controller="Usuarios"
                                            asp-action="IndexLogin">Login</a>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        }
    </header>
    <div class="container teste">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EstudosApiFront
            <img src="@Url.Content("~/images/github.png")" style="width: 25px;">
            <a href="https://github.com/lucasns06/EstudosApiFrontEnd">Github</a> Lucas Nascimento
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>